"added config / subclasses"
MarinaMuttik/webcv pull request #1
Opened 2018-10-17 16:03 UTC by MarinaMuttik

2018-10-17 16:57 UTC, dansteele commented
So can you describe what the issue is here? 

You can use this format to use syntax highlighting in your comments :)

```ruby
class Hello
  def hi
    'asd'
  end
end
```

<img width="83" alt="screenshot 2018-10-17 at 17 57 01" src="https://user-images.githubusercontent.com/9802420/47103000-22e06b80-d236-11e8-8cb3-4462a23b9f82.png">

2018-10-17 17:09 UTC, MarinaMuttik commented
> So can you describe what the issue is here?

So according to <a href="http://recipes.sinatrarb.com/p/middleware/rack_auth_basic_and_digest"> this</a>, using the code I have across .rb and .ru upon running rackup -p 4567 it should display the page as normal, and in /workhistory then require authentication there. But, instead on running rackup all that I get is an error after it reads the require file, goes there and when it reaches the first line of .rb I get: 
```ruby
require 'sinatra/base'
```

> /webcv.rb:1:in `require': cannot load such file -- sinatra/base (LoadError)

And I'm unsure why as the version in master has the same format and is capable of requiring both sinatra & sinatra/base when run directly. Hope that makes some sense..!

2018-10-17 20:57 UTC, dansteele commented
Can you push the latest you got :)

2018-10-18 09:49 UTC, dansteele requested changes
I think it might be worth spending some [more] time working with classes, as in just building your own 

Maybe spend some more time on problem 22 to see how you could refactor it in to more distinct methods, using attr_accessors and instance variables. At the moment everything is in one `perform` method and so you're not making much use of classes.

The reason (I think) that this isn't behaving that way you're expecting it to is because you've got some random classes here, but nothing's 'happening' with them, they just kind of _exist_. Which to me says it's probably a good idea to get more comfortable with classes! :)

I have a 'model answer' for problem 22 which I wrote, which I can share with you after you've spent some more time on it, if you'd like :)

2018-10-18 09:49 UTC, dansteele commented on config.ru
> +  })
Stay on top of your indentation :)

2018-10-18 09:49 UTC, dansteele commented on webcv.rb
> +get '' do
indentation :)

2018-10-18 09:49 UTC, dansteele commented on webcv.rb
> +class Public < Sinatra::Base
The general convention is to have one class per file

2018-10-31 14:38 UTC, merged